buisnesscrm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('crm.urls', namespace='crm')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from decorator_include import decorator_include
from viewsets import ModelViewSet
from . import views
from .views import *
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

urlpatterns = [
    url(r'^$', login_required(views.Dashboard.as_view()), name="dashboard"),
    url(r'^search/$', login_required(views.search), name="search"),

    url(r'^calllogs/$', login_required(views.CallLogList.as_view()), name="calllog_list"),
    url(r'^calllogs/(?P<pk>\d+)/$', login_required(views.CallLogDetail.as_view()), name="calllog_detail"),
    url(r'^calllogs/create/$', login_required(views.CreateCallLog.as_view()), name="calllog_create"),
    url(r'^calllogs/(?P<pk>\d+)/update/$', login_required(views.UpdateCallLog.as_view()), name="calllog_update"),
    url(r'^calllogs/(?P<pk>\d+)/delete/$', login_required(views.DeleteCallLog.as_view()), name="calllog_delete"),

    url(r'^stages/$', login_required(views.StageList.as_view()), name="stage_list"),
    url(r'^stages/(?P<pk>\d+)/$', login_required(views.StageDetail.as_view()), name="stage_detail"),
    url(r'^stages/create/$', login_required(views.CreateStage.as_view()), name="stage_create"),
    url(r'^stages/(?P<pk>\d+)/update/$', login_required(views.UpdateStage.as_view()), name="stage_update"),
    url(r'^stages/(?P<pk>\d+)/delete/$', login_required(views.DeleteStage.as_view()), name="stage_delete"),

    url(r'^companies/$', login_required(views.CompanyList.as_view()), name='company_list'),
    url(r'^companies/(?P<pk>\d+)/$', login_required(views.CompanyDetail.as_view()), name="company_detail"),
    url(r'^companies/create/$', login_required(views.CreateCompany.as_view()), name='company_create'),
    url(r'^companies/(?P<pk>\d+)/update/$', login_required(views.UpdateCompany.as_view()), name="company_update"),
    url(r'^companies/(?P<pk>\d+)/delete/$', login_required(views.DeleteCompany.as_view()), name="company_delete"),

    url(r'^opportunties/$', login_required(views.OpportunityList.as_view()), name='opportunity_list'),
    url(r'^opportunties/(?P<pk>\d+)/$', login_required(views.OpportunityDetail.as_view()), name="opportunity_detail"),
    url(r'^opportunties/create/$', login_required(views.CreateOpportunity.as_view()), name='opportunity_create'),
    url(r'^opportunties/(?P<pk>\d+)/update/$', login_required(views.UpdateOpportunity.as_view()), name="opportunity_update"),
    url(r'^opportunties/(?P<pk>\d+)/delete/$', login_required(views.DeleteOpportunity.as_view()), name="opportunity_delete"),

    url(r'^opportuntystages/(?P<pk>\d+)/$', login_required(views.OpportunityStageDetail.as_view()), name="opportunitystage_detail"),

    url(r'^reminders/$', login_required(views.ReminderList.as_view()), name='reminder_list'),
    url(r'^reminders/(?P<pk>\d+)/$', login_required(views.ReminderDetail.as_view()), name="reminder_detail"),
    url(r'^reminders/create/$', login_required(views.CreateReminder.as_view()), name='reminder_create'),
    url(r'^reminders/(?P<pk>\d+)/update/$', login_required(views.UpdateReminder.as_view()), name="reminder_update"),
    url(r'^reminders/(?P<pk>\d+)/delete/$', login_required(views.DeleteReminder.as_view()), name="reminder_delete"),

    url(r'^campaigns/$', login_required(views.CampaignList.as_view()), name='campaign_list'),
    url(r'^campaigns/(?P<pk>\d+)/$', login_required(views.CampaignDetail.as_view()), name="campaign_detail"),
    url(r'^campaigns/create/$', login_required(views.CreateCampaign.as_view()), name='campaign_create'),
    url(r'^campaigns/(?P<pk>\d+)/update/$', login_required(views.UpdateCampaign.as_view()), name="campaign_update"),
    url(r'^campaigns/(?P<pk>\d+)/delete/$', login_required(views.DeleteCampaign.as_view()), name="campaign_delete"),

    url(r'^contacts/$', login_required(views.ContactList.as_view()), name='contact_list'),
    url(r'^contacts/(?P<pk>\d+)/$', login_required(views.ContactDetail.as_view()), name="contact_detail"),
    url(r'^contacts/create/$', login_required(views.CreateContact.as_view()), name='contact_create'),
    url(r'^contacts/(?P<pk>\d+)/update/$', login_required(views.UpdateContact.as_view()), name="contact_update"),
    url(r'^contacts/(?P<pk>\d+)/delete/$', login_required(views.DeleteContact.as_view()), name="contact_delete"),

    #url('', decorator_include(login_required, include(OpportunityViewSet().urls))),

    #url('', decorator_include(login_required, include(ModelViewSet(Stage).urls))),
    #url('', decorator_include(login_required, include(StageViewSet().urls))),
]

crm/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

crm/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import FormView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.db.models import Count
import datetime
from itertools import chain

from viewsets import ModelViewSet
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

def search(request):
    if request.method == 'GET':
        if request.GET.get('q'):
            contact_results = []
            opp_results =  []
            company_results =  []
            search_words = "%s" % (request.GET.get('q'))
            search_word_list = search_words.split(' ')
            for search_word in search_word_list:
                print search_word
                contact_firstname = Contact.objects.filter(first_name__icontains = search_word)
                contact_lastname = Contact.objects.filter(last_name__icontains = search_word)
                contact_company = Contact.objects.filter(company__name__icontains = search_word)
                opp_firstname = Opportunity.objects.filter(contact__first_name__icontains = search_word)
                opp_lastname = Opportunity.objects.filter(contact__last_name__icontains = search_word)
                opp_stage = Opportunity.objects.filter(stage__name__icontains = search_word)
                opp_company = Opportunity.objects.filter(company__name__icontains = search_word)
                company = Company.objects.filter(name__icontains = search_word)
                contact_results = contact_results + list(contact_firstname) + list(contact_lastname) + list(contact_company)
                opp_results = opp_results + list(opp_firstname) + list(opp_lastname) + list(opp_stage) + list(opp_company)
                company_results = company_results + list(company)

            return render_to_response('crm/search_results.html', {'search':search_words, 'contacts': contact_results, 'opps': opp_results, 'companies': company_results}, context_instance=RequestContext(request))

    return render_to_response('crm/search_results.html', context_instance=RequestContext(request))

class Dashboard(ListView):
    model = OpportunityStage
    template_name = "crm/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)

        #Adding OpportunityStages to the templates' context
        context["reminders"] = Reminder.objects.all().order_by('-date')[:5]
        context["opportunity_stages"] = OpportunityStage.objects.all().order_by('-time_stamp')[:5]
        context["stage_by_opp"] = Stage.objects.order_by('-order').annotate(opp_count = Count('opportunity'))
        context["opp_users"] = User.objects.filter(opportunitystage__stage__value = 100).annotate(num_opp=Count('opportunitystage'))[:5]


        return context

#class StageViewSet(ModelViewSet):
#    model = Stage
#    fields = ['name', 'order', 'descripton', 'value']
#    #success_url = reverse_lazy('crm:stage_list')

class CallLogList(ListView):
    model = CallLog

class CallLogDetail(DetailView):
    model = CallLog

class CreateCallLog(CreateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class UpdateCallLog(UpdateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class DeleteCallLog(DeleteView):
    model = CallLog
    success_url = reverse_lazy('crm:calllog_list')

class StageList(ListView):
    model = Stage
    queryset = Stage.objects.order_by('order')

class StageDetail(DetailView):
    model = Stage

class CreateStage(CreateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class UpdateStage(UpdateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class DeleteStage(DeleteView):
    model = Stage
    success_url = reverse_lazy('crm:stage_list')

class CompanyList(ListView):
    model = Company

class CompanyDetail(DetailView):
    model = Company

class CreateCompany(CreateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class UpdateCompany(UpdateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class DeleteCompany(DeleteView):
    model = Company
    success_url = reverse_lazy('crm:company_list')

class OpportunityList(ListView):
    model = Opportunity

    def get_context_data(self, **kwargs):
        context = super(OpportunityList, self).get_context_data(**kwargs)

        #Adding OpportunityStages to the templates' context
        context["opportunity_stages"] = OpportunityStage.objects.order_by('-time_stamp')

        return context

class OpportunityDetail(DetailView):
    model = Opportunity

class CreateOpportunity(CreateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')


class UpdateOpportunity(UpdateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')

    def form_valid(self, form):
        opportunity = form.save(commit=False)

	if opportunity.stage.value != self.get_object().stage.value:
		opportunity_stage = OpportunityStage()
		opportunity_stage.opportunity = opportunity
		opportunity_stage.stage = form.cleaned_data['stage']
		opportunity_stage.user = self.request.user
		opportunity_stage.save()

        opportunity.save()

        return super(UpdateOpportunity, self).form_valid(form)

class DeleteOpportunity(DeleteView):
    model = Opportunity
    success_url = reverse_lazy('crm:opportunity_list')

class OpportunityStageDetail(DetailView):
    model = OpportunityStage

#class OpportunityViewSet(ModelViewSet):
#    model = Opportunity
#    fields = ['stage', 'company', 'contact', 'value', 'source', 'user', 'create_date']

class ReminderList(ListView):
    model = Reminder
    queryset = Reminder.objects.order_by('completed').order_by('-date')

class ReminderDetail(DetailView):
    model = Reminder

class CreateReminder(CreateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class UpdateReminder(UpdateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class DeleteReminder(DeleteView):
    model = Reminder
    success_url = reverse_lazy('crm:reminder_list')

class CampaignList(ListView):
    model = Campaign

class CampaignDetail(DetailView):
    model = Campaign

class CreateCampaign(CreateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class UpdateCampaign(UpdateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class DeleteCampaign(DeleteView):
    model = Campaign
    success_url = reverse_lazy('crm:campaign_list')

class ContactList(ListView):
    model = Contact

class ContactDetail(DetailView):
    model = Contact

class CreateContact(CreateView):
    model = Contact
    fields = ['company','first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class UpdateContact(UpdateView):
    model = Contact
    fields = ['company','first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class DeleteContact(DeleteView):
    model = Contact
    success_url = reverse_lazy('crm:contact_list')

crm/templates/crm/calllog_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ calllog.name }}?{% endblock %}

{% block content %}

<div style="text-align:center;">
  <form action="." method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete {{ calllog.name }}?</h3>
    <button style="margin-right:20px;" class="btn btn-primary">Delete</button>
    <a class="btn btn-link" href="{% url 'crm:calllog_detail' calllog.id %}">Cancel</a>
  </form>
</div>

{% endblock %}

crm/templates/crm/calllog_list.html
{% extends 'base.html' %}

{% block title %}Call Logs{% endblock %}

{% block content %}
  <a class="btn btn-success" style="margin-bottom:20px;" href="{% url 'crm:calllog_create' %}">Create a New Call Log</a>

  <div class="list-group">
    <a href="#" class="list-group-item active">
     Call Logs
    </a>
    {% for calllog in calllog_list %}
      <a class="list-group-item" href="{% url 'crm:calllog_detail' calllog.id %}">{{ calllog }}</a>
    {% endfor %}
  </div>

{% endblock %}

crm/templates/crm/campaign_detail.html
{% extends 'base.html' %}

{% block title %}Campaign {{ campaign.name }}{% endblock %}

{% block content %}

  <table class="table table-striped">
    <thead>
      <tr class="success">
        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ campaign.name }}</td>
        <td>{{ campaign.description }}</td>
        <td><a class="btn btn-warning" href="{% url 'crm:campaign_update' campaign.id %}">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'crm:campaign_delete' campaign.id %}">Delete</a></td>
      </tr>
    </tbody>
  </table>

{% endblock %}

crm/templates/crm/company_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ company.name }}?{% endblock %}

{% block content %}

<div style="text-align:center;">
  <form action="." method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete {{ company.name }}?</h3>
    <button style="margin-right:20px;" class="btn btn-primary">Delete</button>
    <a class="btn btn-link" href="{% url 'crm:company_detail' company.id %}">Cancel</a>
  </form>
</div>

{% endblock %}

crm/templates/crm/company_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}{% if company %}Upate Company {{ company.name }} {% else %} Create a New Company {% endif %}{% endblock %}

{% block content %}

<div class="well bs-component">
  <form class="form-horizontal" action="." method="post" role="form">
    {% csrf_token %}
    <fieldset>
      <legend class="col-lg-offset-1">{% if company %}Upate Company {{ company.name }} {% else %} Create a New Company {% endif %}</legend>
    {% for field in form %}
    <div class="form-group">
      <div class="col-lg-2 control-label">
        {{ field.label_tag }}
      </div>
      <div class="col-lg-10">
        {% render_field field class+="form-control" %}
        <span class="text-success helper-block">{{ field.help_text }}</span>
      </div>
    </div>
    {% endfor %}
    <button class="col-lg-offset-10 col-lg-2 btn btn-primary">{% if company %}Upate {% else %} Create {% endif %}</button>
    </fieldset>
  </form>
</div>

{% endblock %}

crm/templates/crm/contact_list.html
{% extends 'base.html' %}

{% block title %}Contacts{% endblock %}

{% block content %}
  <a class="btn btn-success" style="margin-bottom:20px;" href="{% url 'crm:contact_create' %}">Create a New Contact</a>

  <div class="list-group">
    <a href="#" class="list-group-item active">
     Contacts
    </a>
    {% for contact in contact_list %}
      <a class="list-group-item" href="{% url 'crm:contact_detail' contact.id %}">{{ contact}}</a>
    {% endfor %}
  </div>

{% endblock %}

crm/templates/crm/dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}CRM Dashboard{% endblock %}
{% block extrascripts %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['User', 'Opportunities Closed'],
          {% for stage in stage_by_opp %}
          ['{{ stage.name }}', {{ stage.opp_count }}],
          {% endfor %}
        ]);
        var options = {
          // title: 'My Daily Activities'
          // legend: 'none',
          is3D: true,
          chartArea: {left:20, top:20, width:'100%', height:'100%'},
          legend: {textStyle: {color: 'white', fontSize: 16}},
          backgroundColor: '#303030',
          slices: {0: {color: '#00bc8c'}, 1: {color: '#337ab7'}, 2: {color: '#3498db'}, 3: {color: '#f39c12'}, 4: {color: '#e74c3c'}, 5: {color: '#00bc8c'}, 6: {color: '#337ab7'}, 7: {color: '#3498db'}, 8: {color: '#f39c12'}, 9: {color: '#e74c3c'}}
        };
        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
      }
    </script>

    <style>
      .btn-circle {
        border-radius: 30px;
        line-height: 1.5;
        font-size: 12px;
      }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="jumbotron">
                <h1>ACME, Inc. CRM</a>
                <p>Let's go manage those sales relationships...</p>
             </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Upcoming Reminders
                </div>
                <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Opportunity</th>
                        <th>Note</th>
                        <th style="min-width: 120px">Due Date</th>
                    </tr>
                    {% for reminder in reminders %}
                    <tr>
                        <td><a href="#">{{ reminder.opportunity }}</a></td>
                        <td>{{ reminder.note }}</td>
                        <td>{{ reminder.date|date:"j M Y" }}</td>
                    </tr>
                    {% endfor %}
                </table>
                    <div class="pull-right">
                    <a href="{% url 'crm:reminder_create' %}" class="btn btn-info btn-circle glyphicon glyphicon-plus" title="Create New Reminder"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Newest Opportunities
                </div>
                <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Opportunity</th>
                        <th>Stage</th>
                        <th>Value</th>
                        <th>Creation Date</th>
                    </tr>
                    {% for opp in opportunity_stages %}
                    <tr>
                        <td><a href="{% url 'crm:opportunity_detail' opp.opportunity.id %}" class="text-info">{{ opp.opportunity.company }}</a></td>
                        <td>{{ opp.stage }}</td>
                        <td>${{ opp.opportunity.value|intcomma }}</td>
                        <td>{{ opp.time_stamp|date:"j M Y" }}</td>
                    </tr>
                    {% endfor %}
                </table>
                        <div class="pull-right">
                        <a href="{% url 'crm:opportunity_create' %}" class="btn btn-success btn-circle glyphicon glyphicon-plus" title="Create New Reminder"></a>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Opportunities By Stage
                </div>
                <div class="panel-body">
                    <div id="piechart" style="width:500px; height: 400px; color:white;"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Top Producers
                </div>
                <div class="panel-body">
                    <table class="table">
                    <tr>
                        <th>Name</th>
                        <th>Opportunities Closed</th>
                    </tr>
                    {% for user in opp_users %}
                    <tr>
                        <td>{% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user }}{% endif %}</td>
                        <td>{{ user.num_opp }}</td>
                    </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

crm/templates/crm/form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crm_extras %}

{% block title %}{% if stage %}Upate Stage {{ stage.name }} {% else %} Create a New Call Log{% endif %}{% endblock %}

{% block content %}

{{ stage|to_class_name }}
{{ calllog|to_class_name }}

<div class="well bs-component">
  <form class="form-horizontal" action="." method="post" role="form">
    {% csrf_token %}
    <fieldset>
      <legend class="col-lg-offset-1">{% if stage %}Upate Stage {{ stage.name }} {% else %} Create a New Stage {% endif %}</legend>
    {% for field in form %}
    <div class="form-group">
      <div class="col-lg-2 control-label">
        {{ field.label_tag }}
      </div>
      <div class="col-lg-10">
        {% render_field field class+="form-control" %}
        <span class="text-success helper-block">{{ field.help_text }}</span>
      </div>
    </div>
    {% endfor %}
    <button class="col-lg-offset-10 col-lg-2 btn btn-primary">{% if stage %}Upate {% else %} Create {% endif %}</button>
    </fieldset>
  </form>
</div>

{% endblock %}

crm/templates/crm/opportunity_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ opportunity.name }}?{% endblock %}

{% block content %}

<div style="text-align:center;">
  <form action="." method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete the Opportunity with {{ opportunity }}?</h3>
    <button style="margin-right:20px;" class="btn btn-primary">Delete</button>
    <a class="btn btn-link" href="{% url 'crm:opportunity_detail' opportunity.id %}">Cancel</a>
  </form>
</div>

{% endblock %}

crm/templates/crm/opportunity_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}{% if opportunity %}Upate Opportunity {{ opportunity.name }} {% else %} Create a New Opportunity{% endif %}{% endblock %}

{% block content %}

<div class="well bs-component">
  <form class="form-horizontal" action="." method="post" role="form">
    {% csrf_token %}
    <fieldset>
      <legend class="col-lg-offset-1">{% if opportunity %}Upate Opportunity {{ opportunity.name }} {% else %} Create a New Opportunity {% endif %}</legend>
    {% for field in form %}
    <div class="form-group">
      <div class="col-lg-2 control-label">
        {{ field.label_tag }}
      </div>
      <div class="col-lg-10">
        {% render_field field class+="form-control" %}
        <span class="text-success helper-block">{{ field.help_text }}</span>
      </div>
    </div>
    {% endfor %}
    <button class="col-lg-offset-10 col-lg-2 btn btn-primary">{% if opportunity %}Upate {% else %} Create {% endif %}</button>
    </fieldset>
  </form>
</div>

{% endblock %}

crm/templates/crm/opportunity_list.html
{% extends 'base.html' %}

{% block title %}Opportunities{% endblock %}

{% block content %}
  <a class="btn btn-success" style="margin-bottom:20px;" href="{% url 'crm:opportunity_create' %}">Create a New Opportunity</a>

<div class="row">
  <div class="list-group col-lg-6">
    <a href="#" class="list-group-item active">
     Opportunities in Progress
    </a>
    {% for opportunity in opportunity_list %}
    <a class="list-group-item" href="{% url 'crm:opportunity_detail' opportunity.id %}">{{ opportunity }} <span style="float:right;">Stage: {{opportunity.stage }}</span></a>
    {% endfor %}
  </div>

  <div class="list-group col-lg-6">
    <a href="#" class="list-group-item active">
      Successful Opportunities
    </a>
    {% for opps in opportunity_stages %}
    <a class="list-group-item" href="{% url 'crm:opportunitystage_detail' opps.id  %}">{{ opps }}<span style="float:right;">{{ opps.time_stamp }}</span></a>
    {% endfor %}
  </div>
</div>


{% endblock %}

crm/templates/crm/opportunitystage_detail.html
{% extends 'base.html' %}

{% block title %}Opportunity Stages {{ opportunitystage }}{% endblock %}

{% block content %}

  <table class="table table-striped">
    <thead>
      <tr class="success">
        <th>Opportunity</th>
        <th>Stage</th>
        <th>Time Stamp</th>
        <th>User Who Closed Opportunity</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ opportunitystage.opportunity }}</td>
        <td>{{ opportunitystage.stage }}</td>
        <td>{{ opportunitystage.time_stamp }}</td>
        <td>{{ opportunitystage.user }}</td>
      </tr>
    </tbody>
  </table>

{% endblock %}

crm/templates/crm/reminder_detail.html
{% extends 'base.html' %}

{% block title %}Reminder {{ reminder.name }}{% endblock %}

{% block content %}

  <table class="table table-striped">
    <thead>
      <tr class="success">
        <th>Opportunity</th>
        <th>Date</th>
        <th>Note</th>
        <th>Completed</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>#{{ reminder.opportunity }}</td>
        <td>{{ reminder.date }}</td>
        <td>{{ reminder.note }}</td>
        <td>{{ reminder.completed }}</td>
        <td><a class="btn btn-warning" href="{% url 'crm:reminder_update' reminder.id %}">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'crm:reminder_delete' reminder.id %}">Delete</a></td>
      </tr>
    </tbody>
  </table>

{% endblock %}

crm/templates/crm/stage_confirm_delete.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

hello world

{% endblock %}