buisnesscrm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('crm.urls', namespace='crm')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from decorator_include import decorator_include
from viewsets import ModelViewSet
from . import views
from .views import *
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

urlpatterns = [
    url(r'^$', login_required(views.Dashboard.as_view()), name="dashboard"),
    url(r'^search/$', login_required(views.search), name="search"),

    url(r'^calllogs/$', login_required(views.CallLogList.as_view()), name="calllog_list"),
    url(r'^calllogs/(?P<pk>\d+)/$', login_required(views.CallLogDetail.as_view()), name="calllog_detail"),
    url(r'^calllogs/create/$', login_required(views.CreateCallLog.as_view()), name="calllog_create"),
    url(r'^calllogs/(?P<pk>\d+)/update/$', login_required(views.UpdateCallLog.as_view()), name="calllog_update"),
    url(r'^calllogs/(?P<pk>\d+)/delete/$', login_required(views.DeleteCallLog.as_view()), name="calllog_delete"),

    url(r'^stages/$', login_required(views.StageList.as_view()), name="stage_list"),
    url(r'^stages/(?P<pk>\d+)/$', login_required(views.StageDetail.as_view()), name="stage_detail"),
    url(r'^stages/create/$', login_required(views.CreateStage.as_view()), name="stage_create"),
    url(r'^stages/(?P<pk>\d+)/update/$', login_required(views.UpdateStage.as_view()), name="stage_update"),
    url(r'^stages/(?P<pk>\d+)/delete/$', login_required(views.DeleteStage.as_view()), name="stage_delete"),

    url(r'^companies/$', login_required(views.CompanyList.as_view()), name='company_list'),
    url(r'^companies/(?P<pk>\d+)/$', login_required(views.CompanyDetail.as_view()), name="company_detail"),
    url(r'^companies/create/$', login_required(views.CreateCompany.as_view()), name='company_create'),
    url(r'^companies/(?P<pk>\d+)/update/$', login_required(views.UpdateCompany.as_view()), name="company_update"),
    url(r'^companies/(?P<pk>\d+)/delete/$', login_required(views.DeleteCompany.as_view()), name="company_delete"),

    url(r'^opportunties/$', login_required(views.OpportunityList.as_view()), name='opportunity_list'),
    url(r'^opportunties/(?P<pk>\d+)/$', login_required(views.OpportunityDetail.as_view()), name="opportunity_detail"),
    url(r'^opportunties/create/$', login_required(views.CreateOpportunity.as_view()), name='opportunity_create'),
    url(r'^opportunties/(?P<pk>\d+)/update/$', login_required(views.UpdateOpportunity.as_view()), name="opportunity_update"),
    url(r'^opportunties/(?P<pk>\d+)/delete/$', login_required(views.DeleteOpportunity.as_view()), name="opportunity_delete"),

    url(r'^opportuntystages/(?P<pk>\d+)/$', login_required(views.OpportunityStageDetail.as_view()), name="opportunitystage_detail"),

    url(r'^reminders/$', login_required(views.ReminderList.as_view()), name='reminder_list'),
    url(r'^reminders/(?P<pk>\d+)/$', login_required(views.ReminderDetail.as_view()), name="reminder_detail"),
    url(r'^reminders/create/$', login_required(views.CreateReminder.as_view()), name='reminder_create'),
    url(r'^reminders/(?P<pk>\d+)/update/$', login_required(views.UpdateReminder.as_view()), name="reminder_update"),
    url(r'^reminders/(?P<pk>\d+)/delete/$', login_required(views.DeleteReminder.as_view()), name="reminder_delete"),

    url(r'^campaigns/$', login_required(views.CampaignList.as_view()), name='campaign_list'),
    url(r'^campaigns/(?P<pk>\d+)/$', login_required(views.CampaignDetail.as_view()), name="campaign_detail"),
    url(r'^campaigns/create/$', login_required(views.CreateCampaign.as_view()), name='campaign_create'),
    url(r'^campaigns/(?P<pk>\d+)/update/$', login_required(views.UpdateCampaign.as_view()), name="campaign_update"),
    url(r'^campaigns/(?P<pk>\d+)/delete/$', login_required(views.DeleteCampaign.as_view()), name="campaign_delete"),

    url(r'^contacts/$', login_required(views.ContactList.as_view()), name='contact_list'),
    url(r'^contacts/(?P<pk>\d+)/$', login_required(views.ContactDetail.as_view()), name="contact_detail"),
    url(r'^contacts/create/$', login_required(views.CreateContact.as_view()), name='contact_create'),
    url(r'^contacts/(?P<pk>\d+)/update/$', login_required(views.UpdateContact.as_view()), name="contact_update"),
    url(r'^contacts/(?P<pk>\d+)/delete/$', login_required(views.DeleteContact.as_view()), name="contact_delete"),

    #url('', decorator_include(login_required, include(OpportunityViewSet().urls))),

    #url('', decorator_include(login_required, include(ModelViewSet(Stage).urls))),
    #url('', decorator_include(login_required, include(StageViewSet().urls))),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Starter Template for Bootstrap{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Custom Css -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'crm/styles.css' %}">

    <!-- Extra Script -->
    {% block extrascripts %}{% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Buisness CRM</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'crm:dashboard' %}">Dash Board</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact Info<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'crm:company_list' %}">Companies</a></li>
                    <li><a href="{% url 'crm:contact_list' %}">Contacts</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sales Support<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'crm:calllog_list' %}">Call Logs</a></li>
                    <li><a href="{% url 'crm:reminder_list' %}">Reminders</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'crm:opportunity_list' %}">Opportunities</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage CRM<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'crm:campaign_list' %}">Campaigns</a></li>
                    <li><a href="{% url 'crm:stage_list' %}">Stages</a></li>
                </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
          {% else %}
            <li><a href="{% url 'registration_register' %}"> Create Account</a></li>
            <li><a href="{% url 'auth_login' %}"> Log In</a></li>
          {% endif %}
          </ul>
          <div class="pull-right">
            <form method="GET" action="{% url 'crm:search' %}" class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q">
                    <div class="input-group-btn">
                        <button class="btn btn-warning" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
    {% block content %}

    {% endblock %}
    </div><!-- /.container -->


  </body>
</html>